# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
 title: Artists Theme
 # email: samtechdeveloper@gmail.com
 description: "Thinker // Developer // Geek"

 logo: logo.svg

 bg-img: 1.jpg
 
 avatar: face.jpg

 blurb: <p><strong>Sameer specializes in various technical skills. </strong>Most of the things he make are web applications and designs. He also puts efforts into learning latest technologies and crafting next-level skills and develop <a href="http://github.com/SamTechDeveloper">projects</a> with them.</p>
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

 # Build settings
 markdown: kramdown
 permalink: pretty
 sass:
  sass_dir: /assets/css/
  style: pretty
